name: .NET Build for Dev

on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore src/K4ryuuSimpleRanks.csproj
      
    - name: Build
      run: dotnet build src/K4ryuuSimpleRanks.csproj -c Release
      
    # ASIL FIX BURASI: Tüm bin klasörünü tarayıp .dll olan her şeyi getirir
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: SimpleRanks-Final-DLL
        path: "**/bin/Release/**/*.dll"
